name: allcontrypicker
description: A flutter package to select a country from a list of countries.

version: 0.0.1

homepage: https://github.com/MohamedAshraf701/countrypicket

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter


flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2